name = "fps-game-js"
compatibility_date = "2025-01-01"
main="fps-game-js/worker.js"

[[d1_databases]]

binding = "DB"
database_name = "cube_assault-db"
database_id = "ca60677c-f3d2-4baa-942e-e65318fe53aa"


[assets]
directory = "./fps-game-js"
binding = "ASSETS"